### PR TITLE
Adds CLI hooks (IDs) to certain elements

### PR DESCRIPTION
**Pull request by mixn**
Hi guys. :) `v3.6.0` introduced [some breaking changes to the CLI](https://github.com/mixn/carbon-now-cli/issues/39) I’m maintaining and trying to keep in sync (feature-wise).

I texted @mfix22 on Twitter about maybe adding some (non-changing) hooks for the CLI, so this doesn’t happen in the future any more. :)

I hereby added four `id`s for all the things the CLI accesses. Let me know if any changes are needed (maybe namespacing?)… :)

Thanks for being so responsive about this, hope to patch the CLI as soon as this is merged and deployed. :)

🙏

### CODE REVIEW

**Comment by mfix22** [comment]
@mixn thanks for this and sorry about breaking your tool 😬 I updated the id's to have a more consistent naming, and release. Hope that works!

**Comment by mixn** [comment]
@mfix22 No worries at all and thank you for the quick merge and deploy! 👏 Patching the CLI as we speak. _Thanks again! 👍_

**Comment by mixn** [comment]
@mfix22 All the IDs seem to be missing again. 😢

**Comment by mfix22** [comment]
@mixn apologies for this, I am pushing the updates now. Do you have time to add Cypress integration tests that test for the existence of these id's to our existing test suite?

**Comment by mfix22** [comment]
@mixn the release was just pushed — hopefully everything is fixed 👍

**Pull request merged**
