### PR TITLE
Feature: Window Title

### PR DESCRIPTION
**Pull request by molnarmark**
This PR is related to #254.

### CODE REVIEW

**Comment by briandennis** [comment]
@molnarmark can you update this so that the title text is saved to the editor state object?

**Comment by molnarmark** [comment]
Sure! Latest commit does it.

**Comment by jakedex** [comment]
Looks great! Thanks for tackling this, @molnarmark 🎊

**Comment by metaskills** [comment]
I've noticed that I can not get the window title to export using PNG, but it does work with SVG. Is that intentional?

**Comment by mfix22** [comment]
Hey @metaskills can you post a link to an example where it is failing? I just tried it and it is working for me: 
carbon

**Comment by metaskills** [comment]
Thanks for following up, after some testing, I found it does not work in Safari. Work fine in Chrome.

**Pull request merged**
