### PR TITLE
Code split and load prettier dynamically

### PR DESCRIPTION
**Pull request by mfix22**
CC: @farskid

### CODE REVIEW

**Comment by farskid** [comment]
@mfix22 I'll dig into it.

**Comment by mfix22** [comment]
@farskid I am pretty sure Next.js uses Webpack to automatically code split dynamic `import`s

**Comment by farskid** [comment]
@mfix22 Is it gonna be the same way for other parsers too? using dynamic import?

**Comment by mfix22** [comment]
Yes please (:

**Comment by farskid** [comment]
I'm on it :)

**Pull request merged**
