### PR TITLE
Added translation in Brazilian Portuguese

### LINKED ISSUE #538: Translate to Brazilian Portuguese
Hey Carbon team!

I was hoping I could translate your docs to Brazilian Portuguese if that's something you guys would like.

Thanks, Izabela.

### PR DESCRIPTION
**Pull request by izabelacborges**
## Description
Added the translated ptBR README file to the docs folder under `README.ptBR.md` and added a link to it in the original README file.

If there is more files prone to translation, such as the Code of Conduct file and contributing file, let me know and I'll translate those too!

Closes #538

### CODE REVIEW

**Comment by mfix22** [comment]
@izabelacborges for my own curiosity's sake, what is the difference between Brazilian Portuguese and another Portuguese? 🙂 There wouldn't be a way to create a version that works for all dialects of Portuguese would there?

**Comment by mfix22** [comment]
And with my question above, should the file then be called: `README.pt.md`? 🙂

**Comment by izabelacborges** [comment]
Brazilian Portuguese has a mixed origin due to our colonization, so our Portuguese is some kind of European Portuguese mixed with Tupi-Guaraní that is the language the natives used at that time. So several words are different for the same thing/object comparing both languages... there are also some grammar constructs that are different between both languages.

I'd say that people that have European Portuguese as a native language will be able to understand most of the translation, but I can't guarantee they would understand 100% of it.

**Comment by mfix22** [comment]
Cool! Do you mind changing the file to `README.BR.pt.md` or `README.br.pt.md`? I would just like the ISO code to stand alone 🙂

**Comment by mfix22** [comment]
Also please run `yarn contrib:add` and then add yourself under "Translation" 👍

**Comment by izabelacborges** [comment]
> Cool! Do you mind changing the file to `README.BR.pt.md` or `README.br.pt.md`? I would just like the ISO code to stand alone 🙂

Sure! Sorry, I didn't knew there was an ISO code.

Also added all translated README files to .all-contribuitorsrc, added myself as contribuitor and changed the name to README.br.pt.md

**Pull request merged**
