### PR TITLE
Lazy load CSS files

### LINKED ISSUE #81: Lazy load stylesheets for themes

### PR DESCRIPTION
**Pull request by mfix22**
Closes #81

### CODE REVIEW

**Comment by mfix22** [comment]
@jakedex there is a bug currently where if you load state from local storage, the state gets updated appropriately and the theme will be displayed in the CodeMirror instance, but the dropdown selected title does not change (still shows "Seti", for example). Can you take a look and push a fix to this branch?

**Comment by briandennis** [comment]
So this works by loading the CSS at the time when the theme is switched?

**Comment by mfix22** [comment]
@briandennis yeah. Should we handle this? Will up time-to-first-paint.

**Comment by briandennis** [comment]
Yeah, I think it may make more sense to first load either the default theme or the query param theme, then paint, then load all remaining themes. That may be 1) simpler and 2) wouldn't lead to lag on theme switching while the style sheet loads. 

The advantage of your way though is that it only loads the ones you need, so for use cases where total data used matters (like mobile) it would be beneficial. Maybe in the future we can sniff the user agent and use this technique if they're on a phone?

**Comment by mfix22** [comment]
Closing this. Unnecessary for now: 
- Closes #81 

screen shot 2017-10-04 at 8 08 59 pm

**Pull request closed without merging**
