### PR TITLE
Support showLineNumbers option 

### LINKED ISSUE #114: Line numbers settings support

### PR DESCRIPTION
**Pull request by guilhermefloriani**
resolve #114

### CODE REVIEW

**Comment by yeskunall** [comment]
This already has a PR (#116), but can you post a screenshot of your changes?

**Comment by guilhermefloriani** [comment]
Sorry, I saw just when I created this PR.

But anyways, here is the screenshot:

screen shot 2017-10-20 at 13 48 15

**Comment by yeskunall** [comment]
LGTM.

**Comment by mfix22** [comment]
Hey @guilhermefloriani thanks so much for the effort, but like @yeskunall said, #116 beat you to it 😄 

Closing.

**Pull request closed without merging**
