### PR TITLE
fix #38

### LINKED ISSUE #38: Support GraphQL syntax mode

### PR DESCRIPTION
**Pull request by sibelius**
add support to graphql in a hacky way

### CODE REVIEW

**Comment by mfix22** [comment]
@sibelius this actually looks great, but is there any way you can add it to a customer mode like you see for `nim` and `elixir`? There is a straight forward to do this with `CodeMirror. See https://github.com/optick/codemirror-mode-elixir/blob/master/index.js for an example

**Comment by aarohmankad** [comment]
Any updates on this? Happy to take over, but I might need some help starting out.

**Comment by aarohmankad** [comment]
It seems that someone has done the majority of the work for us here: https://github.com/graphql/codemirror-graphql

Now it should be as simple as just importing these modules right?

**Comment by mfix22** [comment]
@aarohmankad like I mentioned above, we would like to follow the examples that `Nim` and `Elixir` started. 

You are correct, it is probably as simple as adding that dependency and adding that mode to `constants.js`.

If you open a new PR and post a screenshot of a GraphQL snippet, I would be happy to merge it in and we will get that out in our next release 😄

**Comment by mfix22** [comment]
Hey all, do you guys have any updates here? Otherwise I will open up a new PR soon.

**Comment by aarohmankad** [comment]
@mfix22 I don't have any updates on my end, school's been taking a lot of my time.

**Comment by sibelius** [comment]
@mfix22 u can open a new PR, tks

**Pull request closed without merging**
