### PR TITLE
Update puppeteer to latest version

### PR DESCRIPTION
**Pull request by sdabhi23**
Update version of puppeteer to address issues with emojis in the output.

### CODE REVIEW

**Comment by sdabhi23** [comment]
@mfix22 I do not have an Apple device to test this. Can you please check and confirm if the issue has been fixed?

**Comment by mfix22** [comment]
@sdabhi23 absolutely! Is this to fix issue #439?

**Comment by sdabhi23** [comment]
@mfix22 yes it was to fix #439, and sorry for not testing it out properly.

**Comment by mfix22** [comment]
I upgraded it in the other PR, and emojis are still not working for me 🤷‍♂️ I am still at a loss on this bug (:

**Comment by sdabhi23** [comment]
@mfix22 I am not able to exactly understand the flow of the app, but from whatever I have understood, I guess it's not a problem with the API, but rather the problem is the way in which Safari encodes the emoji characters.

What I have understood till now is that the conversion from code to image is happening on the server, which should be independent of the client from which the site is being accessed.

**Pull request merged**
