### PR TITLE
Added: XQuery

### PR DESCRIPTION
**Pull request by RohitMidha23**
This PR adds XQuery as a language that carbon would now be compatible with. 

## Description

Made a small change to constants.js and added XQuery as a language that can be used.

### CODE REVIEW

**Comment by RohitMidha23** [comment]
@mfix22 I'm not able to add myself to the contributors list for some reason :/

**Comment by mfix22** [comment]
Hey @RohitMidha23 I'll add you once the PR merges. Instead of adding this specific mode, I'm considering adding the ability to just add your own mode at runtime, so then people can use whichever mode they want, even ones outside the list.

**Comment by RohitMidha23** [comment]
@mfix22 can I work on that?

**Comment by mfix22** [comment]
@RohitMidha23 definitely!

**Comment by RohitMidha23** [comment]
@mfix22 can you merge the Pull Request?

**Comment by mfix22** [comment]
Hey @RohitMidha23 I mentioned this before:

> Hey @RohitMidha23 I'll add you once the PR merges. Instead of adding this specific mode, I'm considering adding the ability to just add your own mode at runtime, so then people can use whichever mode they want, even ones outside the list.

Instead of just adding modes like this to the list, I want to add the ability for people to enter their own modes, and I thought you mentioned you want to work on this? 

If you don't want to, or don't have the time, I can see to it 🙂

**Comment by RohitMidha23** [comment]
@mfix22 I thought you guys were putting out an API to do that so I hadn't started working on it :/

**Pull request merged**
