### PR TITLE
add Cypress integration tests

### PR DESCRIPTION
**Pull request by bahmutov**
Partial solution to #136 

- [x] background color changes
- [x] localStorage

See files cypress/integration for tests. To run locally `npm run cy:open`

screen shot 2018-01-18 at 10 04 17 pm

More info: uses [Cypress.io](https://github.com/cypress-io/cypress) test runner. I have also setup recording of tests and recorded a local run. See https://dashboard.cypress.io/#/projects/3tgxx3/runs/000f1338-9007-461a-9b9a-f483cbcaedec

screen shot 2018-01-18 at 10 05 26 pm

There are no failing tests but there is (although very quick) video

screen shot 2018-01-18 at 10 06 39 pm

Let me know if this makes sense, I can continue adding more tests.

### CODE REVIEW

**Comment by mfix22** [comment]
@bahmutov this is absolutely incredible! I want to pull this locally and run it to check it out before merging but this is awesome! 👍 Definitely want to eventually get this set up to run with a auto-now-deploy (see #159) and add it to our Travis job

**Comment by bahmutov** [comment]
Perfect, glad this looks useful. Try it locally, ask me anything unclear either here or on https://twitter.com/bahmutov

PS: Have you seen https://github.com/bahmutov/now-pipeline for deploying with now from CI?

**Comment by mfix22** [comment]
@bahmutov thank you so much. This is huge for us!

Yes I have seen `now-pipeline`, but i totally forgot about it, and I'm clearly not doing to well over here #159 hahaha 😆 Once we expand our Now workflow I will probably move over too it. 

Also do you know how to deploy for a certain team? `--team=dawn` is not working for me right now.

Finally, is there a way to transfer the Cypress project over to me? 😄

**Comment by bahmutov** [comment]
Haha, I have not implemented team deploys in `now-pipeline`, but I did see your commits to get deploy to work ;) Keep up the good fight and if manual deploy is problematic, we can discuss using `now-pipeline` - it has some sweet features like testing unique url first, and switching alias only if tests pass.

So to transfer project - unfortunately our dashboard does not allow transferring project if we do not share an organization in common. For now I removed the project id from `cypress.json`, so if you start Cypress locally and click "Runs" you can just setup it for yourself.

screen shot 2018-01-19 at 9 46 53 am

Typically I would just make a public project under my own name

screen shot 2018-01-19 at 9 47 02 am

**Comment by mfix22** [comment]
This is so awesome. Thank you @bahmutov. I'm adding you to our contributors section, but let me know if you don't want to be included 😄 

And I'm definitely going to configure `now-pipeline` once we get more e2e-tests written! Your software is amazing!

**Pull request merged**
