### PR TITLE
Add Tomorrow Night - Bright theme

### PR DESCRIPTION
**Pull request by NARKOZ**
This pull request adds support for the most popular editor theme -
 https://github.com/chriskempson/tomorrow-theme

### CODE REVIEW

**Comment by mfix22** [comment]
Can you post a screenshot of the new theme?

**Comment by NARKOZ** [comment]
carbon

**Comment by NARKOZ** [comment]
@mfix22 when will this theme appear at https://carbon.now.sh?

**Comment by briandennis** [comment]
@NARKOZ it will be up sometime this week 👍

**Pull request merged**
