### PR TITLE
Add carbon community to footer

### PR DESCRIPTION
**Pull request by mittalyashu**
## Description

Added a link in the footer for joining the [carbon community](https://spectrum.chat/carbon-now).

image

### CODE REVIEW

**Comment by mfix22** [comment]
As of right now, we are going to to leave it on our README alone until there is more interest. If people start engaging more, and we have access to moderate the channels, then we can reconsider adding it to our lander.

**Comment by mittalyashu** [comment]
> we have access to moderate the channels

I can transfer the community to you, I have no issues. 😀

**Comment by mfix22** [comment]
That would be great!

**Comment by mittalyashu** [comment]
@mfix22 The carbon community has been transferred to you. Now you can merge this pull request.

**Pull request closed without merging**
