### PR TITLE
🇯🇵 Update Japanese documents to follow original documents

### PR DESCRIPTION
**Pull request by munierujp**
I've updated Japanese documents to follow original documents (from 2bf33aa to 1e5a173)

### CODE REVIEW

**Comment by mfix22** [comment]
Thank you! :pray:

@uraway can you give this a look and either leave comments or approve, whenever you get a change. Thank you both!

**Comment by uraway** [comment]
@munierujp Thank you!

**Comment by mfix22** [comment]
@all-contributors add @munierujp for translation

**Comment by mfix22** [comment]
@all-contributors add @munierujp for translation

**Pull request merged**
