### PR TITLE
Add Carbonize to README

### PR DESCRIPTION
**Pull request by boyvanamstel**
After peppering you with [Safari related issues 😅](https://github.com/dawnlabs/carbon/issues?q=is%3Aissue+is%3Aclosed+author%3Aboyvanamstel), I've finally released my macOS wrapper for Carbon. It's currently [climbing the ranks on Product Hunt](https://www.producthunt.com/posts/carbonize). I'm pretty stoked about how it turned out and would love to know what you think.

export windows

I thought it might be cool to add it to your README as well. That's where the PR comes in.

I've done my best to attribute your work wherever I can. Let me know if you think it's sufficient.

The app is free and [available on the Mac App Store](https://www.dangercove.com/carbonize/appstore).

## Description

Carbonize wraps carbon.now.sh in a `WKWebView` and adds a bunch of features you'd expect from a native app:

* Dragging and dropping code onto the Dock icon to load it automatically.
* Using the Services menu to easily send selected text to Carbon.
* Bespoke floating preview windows that allow you to drag images into other apps or sites.

By leaving your editor intact I'm confident the desktop wrapper can retain feature parity with the site fairly easily.

(Btw. I noticed the commit hook mangled the contributors overview, so I committed without activating the hooks. I also tried running `yarn contrib:add boyvanamstel`, but it failed with `is/are invalid contribution type(s)`. Even on a clean branch it threw the same error. 🤷‍♂️)

### CODE REVIEW

**Comment by mfix22** [comment]
@boyvanamstel cool! I'll run the contribution script for you. 

However, I want to update the copy added to the README since Carbon already has drag-and-drop... is it not working for you on Carbon?

**Comment by mfix22** [comment]
BTW I really appreciate you calling out our company on your site btw 🙏

**Comment by boyvanamstel** [comment]
> However, I want to update the copy added to the README since Carbon already has drag-and-drop... is it not working for you on Carbon?

I should’ve been more specific. With drag and drop I meant dragging and dropping of the exported image into other apps through the new save preview windows that pop up, and dragging and dropping code onto the Dock icon.

How about:

a macOS wrapper that natively integrates with the OS and adds cool features like dragging and dropping exported images into other apps

**Comment by mfix22** [comment]
@boyvanamstel gotcha! 🙂 

I would like it to be more succinct. What about: "A MacOS wrapper with extended native features"

**Comment by boyvanamstel** [comment]
> @boyvanamstel gotcha! 🙂
> 
> I would like it to be more succinct. What about: "A MacOS wrapper with extended native features", just to keep a similar tone with the rest of the examples

That’s alright. Please make sure you put the caps in the right places though, or Apple will find you. ;)

It’s macOS.

**Comment by mfix22** [comment]
I had no idea! Thanks! 👍

**Pull request merged**
