### PR TITLE
Add support for Verminal theme 💅

### PR DESCRIPTION
**Pull request by vernondegoede**
This change adds a new custom theme to Carbon, based on [Verminal (a Hyper theme)](https://github.com/defringe/verminal).

image

## Description
- It comes with Framer Syntax highlighting (more info: https://twitter.com/framer/status/986977769035845632)
- If the clients browser supports vibrancy (the `backdrop-filter` property), vibrancy will be applied. This property is supported in Safari and on Chrome (although its [behind the "Experimental Web Platform features" feature flag](https://bugs.chromium.org/p/chromium/issues/detail?id=520585)).
- If the clients browser does **not** support this property, we will fallback to a slightly transparent background.
- I noticed there was no `.env.example` file, which is useful for developers to see which env variables are available.

Keep up the good work! 🍻

### CODE REVIEW

**Comment by mfix22** [comment]
Whoa! From the creator himself! Congrats on the Verminal boost after the Hyper 2.0 launch, @vernondegoede  😄

**Comment by vernondegoede** [comment]
❤️

Thanks!

**Comment by vernondegoede** [comment]
Any indication when this will be shipped?

**Comment by mfix22** [comment]
Very soon! We just have a couple PRs that we wanted to get in first, but if we don’t get to them today I’ll release tonight

**Comment by vernondegoede** [comment]
Sweet! 🎉

**Comment by mfix22** [comment]
@vernondegoede just released! Would love to have you tag us in a tweet when you use it ♥️

**Comment by vernondegoede** [comment]
Cool! Of course :) Will tweet about it with some accounts this afternoon (European time).

**Pull request merged**
