### PR TITLE
Adding VS Code's Night Owl theme

### PR DESCRIPTION
**Pull request by wistcc**
## Purpouse
This PR adds the VS Code's Night Owl theme as it was asked here https://twitter.com/fixitup2/status/1001672452588498944

## Description
This is a theme created by @sdras and it was asked to be added to Carbon as you can see on that Twitter thread.

Since Carbon is not so configurable (theme wise) as VS Code is, I wasn't able to make this theme to look the same as it looks in VS Code. This is how it looks here in Carbon:

image
image

Please, @sdras let me know if you want me to change some color (or style) to be more in line with your theme and @mfix22 let me know if I missed something in the code.

I hope you like guys like this, thanks.

### CODE REVIEW

**Comment by mfix22** [comment]
@wistcc thanks for the help! I definitely want @sdras to verify on this one, because it really is all about the colors (: We will happily accept this PR once she does 😄

**Comment by sdras** [comment]
Thank you! I'm going to set it up and take a look in the next few days, to make sure it's correct, but I really appreciate you doing this :) Stay tuned.

**Comment by mfix22** [comment]
Hey @sdras does this look good 😄 Just wondering if you have an update. Really appreciate you reviewing this random PR 😂

**Comment by kentcdodds** [comment]
Maybe this could get merged as-is and bugs can get fixed later if they're identified :)

**Comment by mfix22** [comment]
@sdras let us know if you see issues! (:

**Comment by sdras** [comment]
Sounds good! I'm really really busy this month and this was lower priority than everything else on fire, but you're right, I don't want to hold up the PR here. I'll be able to check it out later, until then just assume no news is good news :)

**Comment by deadcoder0904** [comment]
@mfix22 Not live yet❓Can't see here

**Comment by mfix22** [comment]
@deadcoder0904  We haven't released yet 😄 ! You can checkout https://github.com/dawnlabs/carbon/releases for when our new versions go out

**Pull request merged**
