### PR TITLE
Update Simplified Chinese README.

### PR DESCRIPTION
**Pull request by f0rb1d**
## Description

As the title goes.

### CODE REVIEW

**Comment by mfix22** [comment]
@racaljk can you review this PR for me please 🙏

**Comment by racaljk** [comment]
it's somewhat  unnecessary to retranslate each title

**Comment by mfix22** [comment]
@racaljk what about for the image description `alt` text?

**Comment by racaljk** [comment]
that's all right

**Comment by mfix22** [comment]
@f0rb1d would it be possible to leave the header translations as is, and just update stuff like the image `alt` tags that were previously untranslated? I really appreciate it and will definitely add you as a contributor

**Comment by f0rb1d** [comment]
@mfix22 Fixed now.

**Comment by mfix22** [comment]
@f0rb1d sorry I think my statement must have been confusing. I mean't _don't_ update the headers that have already been translated, and _only_ change the parts that have not yet been translating and are still in english (like the `alt` tags).

Sorry for the extra work 😬

**Comment by racaljk** [comment]
owner意思是，只将`[English]()`修改为`[中文]()`，其它的如标题翻译保持不变~

**Comment by mfix22** [comment]
Any update here folks? 🙂

**Comment by mfix22** [comment]
Hi @f0rb1d @kelthuzadx can you all come to an agreement, and then I will merge this PR 🙂

**Comment by mfix22** [comment]
Please reopen this PR once you two have come to a consensus 🙂

**Pull request closed without merging**
