### PR TITLE
Filter language list

### PR DESCRIPTION
**Pull request by tool3**
Hi!

I really like carbon, and I missed having the ability to filter the language list.

With your awesome permission, I would like you to see what I did to address that. 

demo

Thanks! 🍻 

Basically just added a keyDown function that filters using a RegExp 😃

### CODE REVIEW

**Comment by tool3** [comment]
@mfix22 is there a place to see the next release features so folks don't write stuff that already exist? 😇

**Comment by mfix22** [comment]
We aren't keeping a traditional CHANGELOG, although we are going to try and keep https://github.com/dawnlabs/carbon/releases up to date, with releases marked "Pre" as having not been deployed to production yet.

**Comment by tool3** [comment]
Gotcha @mfix22.. I can't see anything resembling a language filter in there - but if somehow you realize that you still want this small (but saturated with love) contribution..I'll be more than happy to reopen 😃

**Comment by tool3** [comment]
Just saw #283 in the releases 🙈 .. thanks anyway!

**Pull request closed without merging**
