### PR TITLE
restore offline

### PR DESCRIPTION
**Pull request by hanford**
@mfix22 restore carbon offline!

Sort of weird and something I'll need to document better, but it seems like `next-offline` is requiring that the `exportPathMap` is an async function. It makes sense in the next-offline context, because we're needing to do some weird filesystem stuff, but I don't want to diverge from the `next.js` spec, so when time permits, it's something I'll remove. And I can also ensure that `carbon` is updated as well.

Let me know if you'd like any other style/lint modifications, happy to update the PR.

(just to be sure I simply ran `yarn build && yarn export && cd out && now` and it appeared to be working. 

Here is a screenshot:
image

And a now environment:
https://out-bocovxgwiy.now.sh

Cheers!

https://github.com/hanford/next-offline/pull/19#issuecomment-414841537

### CODE REVIEW

**Comment by mfix22** [comment]
@hanford awesome thanks! Just for future reference, the integration in the comment above always deploys a new version of Carbon, so you don't have to do so manually 👍

**Comment by mfix22** [comment]
@hanford actually check out the new deployment here: https://carbon-gyiszlzous.now.sh/. The Service worker failed to register there too . . . can you take a quick look?

**Comment by hanford** [comment]
@mfix22 very weird! I'll try to take a look today

**Comment by mfix22** [comment]
@hanford could this be related to how the content is served in the OSS version of Now versus the paid? That is one difference between our builds . . .

**Comment by hanford** [comment]
@mfix22 hmm, I don't know if there is a difference though the mime type bug is a little weird.

Since it's your now account, can you go to `https://carbon-gyiszlzous.now.sh/` and verify that a `service-worker.js` file doesn't exist?

**Comment by mfix22** [comment]
@hanford confirmed. No `service-worker.js` file exists.

**Comment by mfix22** [comment]
@hanford that worked. `next export` automatically copies over all the files in `/static`, so it might be worth putting the `service-worker.js` file in `/static` . . . what do you think?

**Comment by mfix22** [comment]
@hanford https://github.com/hanford/next-offline/issues/47
if you want to go through with this, I can submit the PR

**Comment by hanford** [comment]
@mfix22 PR would be awesome!

**Pull request merged**
